//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagementSDKDemo.ARMTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArmTemplateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArmTemplateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceManagementSDKDemo.ARMTemplates.ArmTemplateResources", typeof(ArmTemplateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;siteName&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  },
        ///  &quot;hostingPlanName&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  },
        ///  &quot;siteLocation&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  },
        ///  &quot;serverName&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  },
        ///  &quot;serverLocation&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  },
        ///  &quot;administratorLogin&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  },
        ///  &quot;administratorLoginPassword&quot;: {
        ///    &quot;value&quot;: &quot;GEN-PASSWORD&quot;
        ///  },
        ///  &quot;databaseName&quot;: {
        ///    &quot;value&quot;: &quot;&quot;
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string _201_web_app_sql_database_param {
            get {
                return ResourceManager.GetString("_201_web_app_sql_database_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$schema&quot;: &quot;http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#&quot;,
        ///  &quot;contentVersion&quot;: &quot;1.0.0.0&quot;,
        ///  &quot;variables&quot;: {
        ///    &quot;webApiVersion&quot;: &quot;2015-08-01&quot;,
        ///    &quot;resourceGroupLocation&quot;: &quot;[resourceGroup().location]&quot;,
        ///    &quot;appServicePlanNameTidy&quot;: &quot;[toLower(trim(parameters(&apos;appServicePlanName&apos;)))]&quot;,
        ///    &quot;webAppNameTidy&quot;: &quot;[toLower(trim(parameters(&apos;webAppName&apos;)))]&quot;
        ///  },
        ///  &quot;parameters&quot;: {
        ///    &quot;appServicePlanName&quot;: {
        ///      &quot;type&quot;: &quot;string&quot;
        ///    },
        ///    &quot;sku&quot;: {
        ///      &quot;type&quot;: &quot;string&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTemplate {
            get {
                return ResourceManager.GetString("SampleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;appServicePlanName&quot;: {
        ///        &quot;value&quot;: &quot;&quot;
        ///    },
        ///    &quot;webAppName&quot;: {
        ///        &quot;value&quot;: &quot;&quot;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string SampleTemplate_param {
            get {
                return ResourceManager.GetString("SampleTemplate_param", resourceCulture);
            }
        }
    }
}
